### ISSUE TITLE
support for coconut.ui/tink_hxx

### ISSUE THREAD

**Issue by nadako** [influrium/vscode-haxe-jsx#1]
It would be awesome if this extension was also enabled for [coconut.ui](https://github.com/MVCoconut/coconut.ui) components. I _think_ it's mostly about adding two new "begin" patterns? `function render() '` and `hxx('`?

**Comment by ConstNW** [comment]
Extension update will be published soon.

**Comment by nadako** [comment]
Wow that was quick, thank you very much!
